 <script>
     function add_category() {
         var currentCount = $('form > fieldset > fieldset').length;
         var template = $('form > fieldset > span').data('template');
         template = template.replace(/__index__/g, currentCount);

         $('form > fieldset').append(template);

         return false;
     }
 </script>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('% %s'), '<span class="zf-green">', '</span>') ?></h1>

</div>
<?php 
    // var_dump($suppliers);
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Add Supplier') ?></h3>
            </div>
            <div class="panel-body">
<?php
 // $form->setAttribute('action', $this->url('application', array('action' => 'add')));
 $form->prepare();

 $addresses = $form->get('address');

 // var_dump($address);

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('supplier_id'));
 echo $this->formRow($form->get('name')) . "<br />";
 echo $this->formCollection($addresses);

 echo '<button onclick="return add_category()">Add a new Address</button>';

 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();

?>
            </div>
        </div>
    </div>




</div>
